import images from './images';

export const contacts = [
  {
    id: '1',
    userName: 'John Doe',
    userImg: images.user1,
    isOnline: false,
    lastSeen: '3 Days ago',
    lastMessage: 'How is it going...',
    messageInQueue: 3,
    sentDate: '12/7',
  },
  {
    id: '2',
    userName: 'Marry Lio',
    userImg: images.user2,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'Good morning...',
    messageInQueue: 0,
    sentDate: '12/7',
  },
  {
    id: '3',
    userName: 'Lucia Mustaq',
    userImg: images.user3,
    isOnline: false,
    lastSeen: '2 weeks ago',
    lastMessage: "What's up...",
    messageInQueue: 0,
    sentDate: '12/7',
  },
  {
    id: '4',
    userName: 'Raki Lili',
    userImg: images.user4,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'Send me the link',
    messageInQueue: 0,
    sentDate: 'Today',
  },
  {
    id: '5',
    userName: 'Rakita Devine',
    userImg: images.user5,
    isOnline: false,
    lastSeen: '5 days ago',
    lastMessage: 'We are doing...',
    messageInQueue: 0,
    sentDate: '23/9',
  },
  {
    id: '6',
    userName: 'Aris Yup',
    userImg: images.user6,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'How is it going...',
    messageInQueue: 3,
    sentDate: 'Today',
  },
  {
    id: '7',
    userName: 'Aris Yup',
    userImg: images.user6,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'How is it going...',
    messageInQueue: 3,
    sentDate: '12/7',
  },
  {
    id: '8',
    userName: 'Billy Di',
    userImg: images.user2,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'How is it going...',
    messageInQueue: 3,
    sentDate: '12/7',
  },
  {
    id: '9',
    userName: 'Aris Biu',
    userImg: images.user2,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'How is it going...',
    messageInQueue: 3,
    sentDate: '12/7',
  },
  {
    id: '10',
    userName: 'Advard Cullen',
    userImg: images.user2,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'How is it going...',
    messageInQueue: 3,
    sentDate: '12/7',
  },
  {
    id: '11',
    userName: 'Reema Dutt',
    userImg: images.user2,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'How is it going...',
    messageInQueue: 3,
    sentDate: '12/7',
  },
  {
    id: '12',
    userName: 'Bilal Khan',
    userImg: images.user2,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'How is it going...',
    messageInQueue: 3,
    sentDate: '12/7',
  },
  {
    id: '13',
    userName: 'Nazim Khan',
    userImg: images.user9,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'How is it going...',
    messageInQueue: 3,
    sentDate: '12/7',
  },
  {
    id: '14',
    userName: 'Jammy linn',
    userImg: images.user2,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'How is it going...',
    messageInQueue: 3,
    sentDate: '12/7',
  },
  {
    id: '15',
    userName: 'John wick',
    userImg: images.user2,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'How is it going...',
    messageInQueue: 3,
    sentDate: '12/7',
  },
];
export const list = [
  {
    id: '1',
    userName: 'John',
    userImg: images.user1,
    isOnline: false,
    lastSeen: '3 Days ago',
    lastMessage: 'How is it going...',
    messageInQueue: 3,
    sentDate: '12/7',
  },
  {
    id: '2',
    userName: 'Marry',
    userImg: images.user2,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'Good morning...',
    messageInQueue: 0,
    sentDate: '12/7',
  },
  {
    id: '3',
    userName: 'Lucia',
    userImg: images.user3,
    isOnline: false,
    lastSeen: '2 weeks ago',
    lastMessage: "What's up...",
    messageInQueue: 0,
    sentDate: '12/7',
  },
  {
    id: '4',
    userName: 'Raki',
    userImg: images.user4,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'Send me the link',
    messageInQueue: 0,
    sentDate: 'Today',
  },
  {
    id: '5',
    userName: 'Rakita',
    userImg: images.user5,
    isOnline: false,
    lastSeen: '5 days ago',
    lastMessage: 'We are doing...',
    messageInQueue: 0,
    sentDate: '23/9',
  },
  {
    id: '6',
    userName: 'Arun',
    userImg: images.user6,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'How is it going...',
    messageInQueue: 3,
    sentDate: 'Today',
  },
  {
    id: '7',
    userName: 'Armeen',
    userImg: images.user6,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'How is it going...',
    messageInQueue: 3,
    sentDate: '12/7',
  },
  {
    id: '8',
    userName: 'Ben',
    userImg: images.user2,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'How is it going...',
    messageInQueue: 3,
    sentDate: '12/7',
  },
  {
    id: '9',
    userName: 'Arlene',
    userImg: images.user2,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'How is it going...',
    messageInQueue: 3,
    sentDate: '12/7',
  },
  {
    id: '10',
    userName: 'Advard',
    userImg: images.user2,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'How is it going...',
    messageInQueue: 3,
    sentDate: '12/7',
  },
  {
    id: '11',
    userName: 'Reema',
    userImg: images.user2,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'How is it going...',
    messageInQueue: 3,
    sentDate: '12/7',
  },
  {
    id: '12',
    userName: 'Bilal',
    userImg: images.user2,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'How is it going...',
    messageInQueue: 3,
    sentDate: '12/7',
  },
  {
    id: '13',
    userName: 'Nazim',
    userImg: images.user9,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'How is it going...',
    messageInQueue: 3,
    sentDate: '12/7',
  },
  {
    id: '14',
    userName: 'Jammy',
    userImg: images.user2,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'How is it going...',
    messageInQueue: 3,
    sentDate: '12/7',
  },
  {
    id: '15',
    userName: 'John',
    userImg: images.user2,
    isOnline: true,
    lastSeen: 'Online',
    lastMessage: 'How is it going...',
    messageInQueue: 3,
    sentDate: '12/7',
  },
];
